CREATE TABLE IF NOT EXISTS users
(
    id       BIGSERIAL PRIMARY KEY,
    email    VARCHAR(320) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS users_emails_idx on users (email);

CREATE TABLE IF NOT EXISTS groups
(
    id   BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users_groups
(
    user_id  BIGINT NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    group_id BIGINT NOT NULL REFERENCES groups (id) ON DELETE CASCADE
);
